{% set version = "2.0.0" %}
package:
  name: humanize
  version: {{ version }}

source:
  fn: humanize-{{ version }}.tar.gz
  url: https://github.com/jmoiron/humanize/archive/{{ version }}.tar.gz
  sha256: 44c337facb5635035d2b70524df2300db8640eca48c3a963adebf004191d223b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - humanize

about:
  home: https://github.com/jmoiron/humanize
  license: MIT
  license_file: LICENCE
  summary: Python humanize utilities.

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ocefpaf
